

```
1. 데이터 가져오기
   X, y 데이터와 라벨(supervised learning)  <- 답이 있다. 우린 지금 이걸 하고 있음
   (X, no y 데이터, 노 라벨(unsupervised L)(reinforcement L)  <-  확실한 답 없음)
```



In [ ]:
'''import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import cv2

from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.utils import to_categorical'''

In [ ]:
'''(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

class_labels = ["T-shirt/top","Trouser","Pullover","Dress","Coat","Sandal","Shirt","Sneaker","Bag","Ankle boot"]
print(len(class_labels))'''

In [ ]:
'''X_train_scaled = X_train / 255.0
X_test_scaled = X_test / 255.0
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(20, activation = 'relu'),
    Dense(10, activation = 'softmax')
])
model.summary()

model.compile(optimizer = 'adam',
              loss = 'sparse_categorical_crossentropy',
              metrics = ['accuracy'])

model.fit(X_train_scaled, y_train, epochs = 5)

prediction = model.predict(X_test_scaled)
print(prediction[100])
print(np.argmax(prediction[100]))'''

In [ ]:
'''y_train_ohe = to_categorical(y_train)
print(y_train_ohe[0])
print(y_train[0])
y_test_ohe = to_categorical(y_test)

model.compile(optimizer = 'adam',
              loss = 'categorical_crossentropy',
              metrics = ['accuracy'])
model.fit(X_train_scaled, y_train_ohe, epochs = 5)'''

In [ ]:
'''prediction = model.predict(X_test_scaled)
print(prediction.shape)

print(prediction[9])
print(np.argmax(prediction[9]))
print(y_test[9])

print(prediction[10])
print(np.argmax(prediction[10]))
print(y_test[10])

plt.title(class_labels[np.argmax(prediction)])'''

In [ ]:
import numpy as np

In [ ]:
X = np.arange(1, 3)
print(X)

[1 2]


In [ ]:
#W1 = np.arange(1, 7).reshape((2, 3))
W1 = np.random.randn(6).reshape((2, 3))  #처음 w,b는 랜덤으로 설정됨
print(W1)

[[-0.77287929  0.6401254  -1.6461671 ]
 [-1.47943728  1.01391884 -0.54850198]]


In [ ]:
#B1 = np.arange(1, 4)
B1 = np.random.rand(3) #randn은 양수 음수, rand는 양수
print(B1)

[0.16195206 0.59878885 0.24677032]


In [ ]:
#A1 = np.dot(X, W1) + B1
Z1 = np.dot(X, W1) + B1
print(Z1)

[-3.5698018   3.26675194 -2.49640075]


In [ ]:
def relu(x):
  return np.maximum(0, x)

In [ ]:
A1 = relu(Z1)
print(A1)

[0.         3.26675194 0.        ]


In [ ]:
W2 = np.random.randn(6).reshape((3, 2))
print(W2)

B2 = np.random.rand(2).reshape((1, 2))
print(B2)

Z2 = np.dot(A1, W2) + B2
print(Z2)

A2 = relu(Z2)
print(A2)

[[ 1.00359352  1.5286562 ]
 [ 0.90049058  0.28120745]
 [ 0.21251453 -1.27739932]]
[[0.59602407 0.64066002]]
[[3.53770342 1.55929499]]
[[3.53770342 1.55929499]]


In [ ]:
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

In [ ]:
W3 = np.random.randn(4).reshape((2, 2))
print(W3)

B3 = np.random.rand(2).reshape((1, 2))
print(B3)

Z3 = np.dot(A2, W3) + B3
print(Z3)

y = softmax(Z3)
print(y)

[[-1.10862359  0.80602837]
 [-0.48941109  0.68403037]]
[[0.6201907  0.68422476]]
[[-4.064927    4.60231922]]
[[1. 1.]]


In [1]:
'''def init_network():
  network = {}
  network['W1'] = np.random.randn(6).reshape((2, 3))
  network['B1'] = np.random.rand(3)
  network['W2'] = np.random.randn(6).reshape((3, 2))
  network['B2'] = np.random.rand(2).reshape((1, 2))
  network['W3'] = np.random.randn(4).reshape((2, 2))
  network['B3'] = np.random.rand(2).reshape((1, 2))

def relu(x):
  return np.maximum(0, x)

def softmax(x):
  e_x = np.exp(x - np.max(x))
  return e_x / e_x.sum(axis=0)

def forward(network, x):
  W1, W2, W3 = network['W1'], network['W2'], network['W3']
  B1, B2, B3 = network['B1'], network['B2'], network['B3']
  Z1 = np.dot(x, W1) + B1
  A1 = relu(Z1)
  Z2 = np.dot(A1, W2) + B2
  A2 = relu(Z2)
  Z3 = np.dot(A2, W3) + B3
  y = softmax(Z3)

network = init_network()
x = np.array([1, 2])
y_pred = forward(network, x)
print(y_pred)'''

import numpy as np

def init_network():
    network = {}
    network['W1'] = np.random.randn(6).reshape((2, 3))
    network['B1'] = np.random.rand(3)
    network['W2'] = np.random.randn(6).reshape((3, 2))
    network['B2'] = np.random.rand(2).reshape((1, 2))
    network['W3'] = np.random.randn(4).reshape((2, 2))
    network['B3'] = np.random.rand(2).reshape((1, 2))
    return network

def relu(x):
    return np.maximum(0, x)

def softmax(x):
    e_x = np.exp(x - np.max(x, axis=1, keepdims=True))
    return e_x / e_x.sum(axis=1, keepdims=True)

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    B1, B2, B3 = network['B1'], network['B2'], network['B3']

    # 입력을 2D로 변환
    x = x.reshape(1, -1)

    Z1 = np.dot(x, W1) + B1
    A1 = relu(Z1)
    Z2 = np.dot(A1, W2) + B2
    A2 = relu(Z2)
    Z3 = np.dot(A2, W3) + B3
    y = softmax(Z3)
    return y

network = init_network()
x = np.array([1, 2])
y_pred = forward(network, x)
print(y_pred)


[[0.25774891 0.74225109]]
